language: python
python:
  - "2.7"

env:
  - DJANGO=1.3.7 DB=sqlite
  - DJANGO=1.3.7 DB=postgres
  - DJANGO=1.3.7 DB=mysql
  - DJANGO=1.4.18 DB=sqlite
  - DJANGO=1.4.18 DB=postgres
  - DJANGO=1.4.18 DB=mysql

addons:
  - postgresql: "9.3"

# Install OS dependencies
before_install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - sudo apt-get update -qq
  - sudo apt-get install -y git-core python-dev g++ libtidy-dev pandoc libpq-dev

# Install Python dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - cp deploy/settings_travis.py settings_local.py

before_script:
  - psql -c 'create database comt;' -U postgres
  - mysql -e 'create database comt;'

# Run tests
script:
  - python manage.py test cm

notifications:
  email:
    recipients:
      - dev@abilian.com
    on_success: change
    on_failure: change
