language: python
python:
  - "2.7"

env:
  - DJANGO=1.3.7 DB=sqlite
  - DJANGO=1.3.7 DB=postgres
  - DJANGO=1.3.7 DB=mysql
  - DJANGO=1.4.18 DB=sqlite

matrix:
  allow_failures:
    - env: DJANGO=1.4.18 DB=sqlite
  fast_finish: true

addons:
  postgresql: "9.3"

# Install OS-level dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git-core python-dev g++ libtidy-dev pandoc 
  - sudo apt-get install -y libmysqlclient-dev libpq-dev
  - npm install karma karma-phantomjs-launcher karma-e2e-dsl karma-mocha

# Install Python dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO

before_script:
  - psql -c 'create database comt;' -U postgres
  - mysql -e 'create database comt;'

# Run tests
script:
  - py.test --cov cm --cov-config etc/coverage.rc cm
  - ./tests/e2e/run.sh

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dev@abilian.com
    on_success: change
    on_failure: change

